name: images-comparison
static_sites:
- environment_slug: html
  github:
    branch: master
    deploy_on_push: true
    repo: eclipseo/eclipseo.github.io
  name: images-comparison
  index_document: image-comparison-web/index.html
